### ISSUE TITLE
Can't build minecraft 1.21 on apple silicon

### ISSUE THREAD

**Issue by artemisSystem** [CrackedPolishedBlackstoneBricksMC/minivan#2]
I get the following error:
```
> Could not resolve all files for configuration ':Xplat:compileClasspath'.
   > Could not find lwjgl-freetype-3.3.3-natives-macos-patch.jar (org.lwjgl:lwjgl-freetype:3.3.3).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-macos-patch.jar
```

Curiously using NeoForm instead, i get this:
```
  WARNING: org.lwjgl:lwjgl-freetype:3.3.3:natives-macos-arm64 is not present in the artifact manifest
  ↓ https://libraries.minecraft.net/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-macos-arm64.jar
```
Not sure how related it is, i don't know what the "artifact manifest" is or what the warning even means (i get like 20 of these, but the build works), but neoform seems to get the natives from `libraries.minecraft.net` instead of `repo.maven.apache.org`, so maybe the solution is to just add that as a search location?

**Comment by quat1024** [comment]
Aaaa why does it even do anything with natives, i try to skip them here

https://github.com/CrackedPolishedBlackstoneBricksMC/minivan/blob/c5db5684cac44a713afa185874ef0e6e1bf4760b/src/main/java/agency/highlysuspect/minivan/prov/MinecraftProvider.java#L37

orz...

Really I should delete all the native handling code from minivan, i don't need any of it

**Comment by quat1024** [comment]
Hmm, just found out Github offers Actions runners running Apple Silicon https://github.com/actions/runner-images/issues/9254 that's nice

**Comment by artemisSystem** [comment]
> Aaaa why does it even do anything with natives, i try to skip them here

don't you need them to run the game? oh, right, no runs, yeah that makes sense

**Comment by quat1024** [comment]
I dunno if 1.21 builds at all, actually:

```
Caused by: java.lang.RuntimeException: error analyzing /net/minecraft/bundler/Main.class from C:\Users\quat\.gradle\caches\minivan-cache\minecraft-1.21.1-server.jar
	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:573)
	at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:71)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:522)
	at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:518)
	at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:518)
	at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:71)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:490)
	at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:486)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:571)
	... 7 more
```
Probably just need to update the used version of t-r

**Comment by quat1024** [comment]
im stupid *i* forgot to update minivan 🙃
